#!/usr/bin/env node
// gen-catalog.mjs — regenerate skills/SKILLS.md, the single discoverable skill catalog.
// One table: skill · owner agents (from agents' skills: frontmatter) · "Use when" trigger
// (from each SKILL.md description:). Run from the helmsman SOURCE repo root:
//   node skills/harness-audit/scripts/gen-catalog.mjs          # write skills/SKILLS.md
//   node skills/harness-audit/scripts/gen-catalog.mjs --check  # print to stdout, write nothing
// The audit (catalog-sync check) regenerates in-memory and WARNs if skills/SKILLS.md is stale.
import { readFileSync, readdirSync, existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.argv.find((a) => !a.startsWith("--") && a !== process.argv[0] && a !== process.argv[1]) || process.cwd();
const skillsDir = join(ROOT, "skills");
const vendorDir = join(ROOT, "skills-vendor");
const agentsDir = join(ROOT, "agents");

const fmField = (body, key) => {
  // read a frontmatter scalar (handles `key: value` and `key: >-` folded blocks)
  const m = body.match(new RegExp(`^${key}:\\s*(.*)$`, "m"));
  if (!m) return "";
  let v = m[1].trim();
  if (v === ">-" || v === ">" || v === "|" || v === "") {
    // folded/literal block: take following indented lines
    const after = body.slice(body.indexOf(m[0]) + m[0].length).split("\n");
    const lines = [];
    for (const ln of after) {
      if (/^\s+\S/.test(ln)) lines.push(ln.trim());
      else if (ln.trim() === "") continue;
      else break;
    }
    v = lines.join(" ");
  }
  return v.replace(/\s+/g, " ").trim();
};

// "Use when" extraction: prefer the sentence starting at "Use when", else first sentence.
const useWhen = (desc) => {
  if (!desc) return "";
  const uw = desc.match(/Use when[^.]*\./i);
  if (uw) return uw[0].replace(/\s+/g, " ").trim();
  const first = desc.split(/(?<=\.)\s/)[0];
  return (first || desc).slice(0, 160).trim();
};

// gather owner agents per skill from agents/*.md skills: frontmatter
const owners = {}; // skill -> [agent,...]
if (existsSync(agentsDir)) {
  for (const f of readdirSync(agentsDir).filter((f) => f.endsWith(".md"))) {
    const body = readFileSync(join(agentsDir, f), "utf8");
    const m = body.match(/^skills:\s*\[([^\]]*)\]/m);
    if (!m) continue;
    const agent = f.replace(/\.md$/, "");
    for (const s of m[1].split(",").map((x) => x.trim()).filter(Boolean)) {
      (owners[s] ||= []).push(agent);
    }
  }
}

const collect = (base, kind) => {
  if (!existsSync(base)) return [];
  return readdirSync(base)
    .filter((d) => existsSync(join(base, d, "SKILL.md")))
    .map((d) => {
      const body = readFileSync(join(base, d, "SKILL.md"), "utf8");
      return { name: d, kind, trigger: useWhen(fmField(body, "description")) };
    });
};

const ours = collect(skillsDir, "ours").sort((a, b) => a.name.localeCompare(b.name));
const vendor = collect(vendorDir, "vendor").sort((a, b) => a.name.localeCompare(b.name));

const ownerCell = (name) => {
  const o = owners[name];
  if (!o || o.length === 0) return "_(shared / ritual)_";
  return o.map((a) => `@${a}`).join(", ");
};
const esc = (s) => s.replace(/\|/g, "\\|");

const rows = (list) =>
  list.map((s) => `| \`${s.name}\` | ${ownerCell(s.name)} | ${esc(s.trigger)} |`).join("\n");

const out = `# Helmsman — Skills Catalog (generated)

<!-- GENERATED by skills/harness-audit/scripts/gen-catalog.mjs — do not edit by hand.
     Regenerate: node skills/harness-audit/scripts/gen-catalog.mjs -->

The single place to discover **which skill to use**. Each row: the skill, the agents that
own it (from their \`skills:\` frontmatter), and its "Use when" trigger (from the skill's
\`description:\`). To USE a skill, \`read\` its \`SKILL.md\` — ours under \`.helmsman/skills/<name>/\`,
vendored under \`.opencode/skills/<name>/\` (see operating-rules Rule 4).

## Helmsman skills (ours — ${ours.length})

| Skill | Owner agent(s) | Use when |
|-------|----------------|----------|
${rows(ours)}

## Vendored skills (${vendor.length})

| Skill | Owner agent(s) | Use when |
|-------|----------------|----------|
${rows(vendor)}
`;

if (process.argv.includes("--check")) {
  process.stdout.write(out);
} else {
  writeFileSync(join(ROOT, "skills", "SKILLS.md"), out);
  process.stderr.write(`[gen-catalog] wrote skills/SKILLS.md (${ours.length} ours + ${vendor.length} vendored)\n`);
}
